### ISSUE TITLE
How to setup efficient pipeline triggers

### ISSUE THREAD

**Issue by flyck** [hendriknielaender/double-trouble#375]
Idea for a blogpost. We should only post it if it is cool enough.

More title ideas:
- our efficient gitlab pipeline setup

Our setup in gitlab:
- in MRs
  - deploy Dev & Test is possible immediately (needs: [])
  - run build and test jobs together (more pipeline stages are not better)
  - use install caches and build artifacts, with fallback caches to master in case no package was installed
  - finetune the job triggers (needs: job: install, optional: true)
- in main / master
  - deploy to prod is also possible immediately (a merged MR from a branch will anyway have build & test succeeding, so it is safe to deploy immediately in 99% of the cases)
- review apps for care-free test deployments (link to other blog post)

**Comment by hendriknielaender** [comment]
yeah thats sounds cool, something like:

- "Unlock Lightning-Fast Deployments in GitLab".
- "Slash your GitLab pipeline times with these tips"

Tips:
- Run jobs only when necessary (Skip backend tests when only frontend code has been changed)
  ```yaml
    only:
      changes:
        - apps/example1/**/*
        - shared-dependencies/**/*
  ```
- Caching
  ```yaml
  example-job:
    script:
      - yarn install --frozen-lockfile --check-files
    cache:
      paths:
        - node_modules/
  ```
  
  ```yaml
  variables:
    FF_USE_FASTZIP: "true"
    # These can be specified per job or per pipeline (slowest, slow, default, fast, and fastest)
    ARTIFACT_COMPRESSION_LEVEL: "fastest"
    CACHE_COMPRESSION_LEVEL: "fastest"
  ```
- Pre-install dependencies (docker image)
- Use tiny Linux distros for your CI images
- node specific: bun > pnpm > yarn2 > yarn > npm
